refactor: 메서드 모듈화 및 네비게이트 관련 버그 수정
uswLectureEvaluation/Frontend pull request #32
Opened 2023-01-27 17:14 UTC by truewayy

1. 로컬 스토리지 모듈화 및 적용
2. 로그인 실패 시에도 홈으로 네비게이트 되는 버그 발견 -> 수정
3. 검색, 강의 정보 페이지에서 이전 페이지에 대한 스크롤 상태가 적용되어 화면 해상도에 따라 불편이 야기될 수 있다는 점에서
scrollToTop 메서드를 모듈화하고 적용

2023-01-27 21:28 UTC, tooooo1 requested changes
작업 너무 고생하셨습니다. 몇 가지 피드백 하고 가요!

2023-01-27 21:28 UTC, tooooo1 commented on src/api/ApiController.js
>              }
logout API가 현재 `ApiController.js`와 '`Auth.js` 파일. 두 개에서 선언되고 관리되고 있어요. 하나로 통일해 주어야할 것 같습니다.

2023-01-27 21:28 UTC, tooooo1 commented on src/pages/Login.jsx
> +    auth.login(userId.current.value, password.current.value);
login API는 선언부분에서 then으로 처리되고 있는데 logout은 선언에서 부르기만하고 로직 사용하는 부분에서 then으로 받아서 처리되고 있네요. 통일성이 없다고 느껴지는데요. API를 한 가지로 통일하면 더 좋을 것 같아요.

2023-01-27 21:28 UTC, tooooo1 commented on src/utils/loginStorage.js
>  };
이 함수 이제 더 리팩터링할 수 있을 것 같아요.

```js
export const isLoginStorage = () => {
  return !!localStorage.login;
}
```

다음과 같이 훨신 간결하게 표현할 수 있어요.

2023-01-28 17:30 UTC, truewayy commented
API 상당부분 리팩토링 (컨트롤러에서 토큰 스테이트 관리 및 try.catch 구문으로 에러핸들링)
기존 MUI select -> 커스텀 select 교체 (semester, examType)

2023-01-28 22:45 UTC, tooooo1 approved these changes
이전 코드보다 확실히 좋아진 게 눈에 보이네요! 엄청난 작업량!
고생하셨습니다!

2023-01-28 22:45 UTC, merged